export const columns = [
    { key: 'ID', label: 'id' },
    { key: 'Customer_name', label: 'Name' },
    { key: 'Street', label: 'Street' },
    { key: 'City', label: 'City' },
    { key: 'State', label: 'State' },
    { key: 'Zip_code', label: 'Zip Code' },
    { key: 'Notes', label: 'Notes' },
    { key: 'Terms', label: 'Terms' },
    { key: 'Account_number', label: 'Account Number' },
    { key: 'Tax_id', label: 'Tax ID' },
    { key: 'Balance', label: 'Balance' },
    { key: 'Is_active', label: 'Is Active' },
    { key: 'Is_sub_agency', label: 'Is Sub Agency' },
    { key: 'Language', label: 'Language' },
    { key: 'Slug', label: 'Slug' },
    { key: 'Id_currency', label: 'Currency ID' },
    { key: 'Id_country', label: 'Country ID' },
    { key: 'Irs_share_key', label: 'IRS Share Key' },
    { key: 'Currency_rate', label: 'Currency Rate' },
    { key: 'Agency', label: 'Agency' },
    { key: 'Avoid_deletion', label: 'Avoid Deletion' },
    { key: 'Is_editable', label: 'Is Editable' },
    { key: 'Alias', label: 'Alias' },
    { key: 'Already_used', label: 'Already Used' },
    { key: 'Ab_key', label: 'AB Key' },
    { key: 'Tmc_client_number', label: 'TMC Client Number' },
  ];
