export const columns = [
  { key: 'ID', label: 'id', type: 'number' },
  { key: 'Customer_name', label: 'Name', type: 'string' },
  { key: 'Street', label: 'Street', type: 'string' },
  { key: 'City', label: 'City', type: 'string' },
  { key: 'State', label: 'State', type: 'string' },
  { key: 'Zip_code', label: 'Zip Code', type: 'string' },
  { key: 'Notes', label: 'Notes', type: 'string' },
  { key: 'Terms', label: 'Terms', type: 'number' },
  { key: 'Account_number', label: 'Account Number', type: 'string' },
  { key: 'Tax_id', label: 'Tax ID', type: 'string' },
  { key: 'Balance', label: 'Balance', type: 'string' },
  { key: 'Is_active', label: 'Is Active', type: 'boolean' },
  { key: 'Is_sub_agency', label: 'Is Sub Agency', type: 'boolean' },
  { key: 'Language', label: 'Language', type: 'string' },
  { key: 'Slug', label: 'Slug', type: 'number' },
  { key: 'Id_currency', label: 'Currency ID', type: 'number' },
  { key: 'Id_country', label: 'Country ID', type: 'number' },
  { key: 'Irs_share_key', label: 'IRS Share Key', type: 'string' },
  { key: 'Currency_rate', label: 'Currency Rate', type: 'number' },
  { key: 'Agency', label: 'Agency', type: 'string' },
  { key: 'Avoid_deletion', label: 'Avoid Deletion', type: 'boolean' },
  { key: 'Is_editable', label: 'Is Editable', type: 'boolean' },
  { key: 'Alias', label: 'Alias', type: 'string' },
  { key: 'Already_used', label: 'Already Used', type: 'number' },
  { key: 'Ab_key', label: 'AB Key', type: 'string' },
  { key: 'Tmc_client_number', label: 'TMC Client Number', type: 'string' },
];
